# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Reuse - Repair' do
        source 'https://github.com/CocoaPods/Specs.git'
        platform :ios, '9.1'
        pod 'GoogleMaps'

pod 'ReachabilitySwift', :git => 'https://github.com/ashleymills/Reachability.swift'
end

