-- DATABASE DATA
-- Name:  Group 2
-- Assignment:  Final Project
-- Date:  2.19.16
-- TO UPLOAD, IMPORT IN MYPHPADMIN AFTER UPLOADING databaseTables.sql

/*  UNCOMMENT THIS BLOCK IF USING MYSQL DATABASE THAT ALLOWS MORE THAN ONE DATABASE */
/* OSU'S MYSQL DATABASE DOES NOT ALLOW THIS SO THIS BLOCK NEEDS TO REMAIN COMMENTED IF LOADING TO YOUR OSU DATABASE */

DROP TABLE IF EXISTS adminTable;
DROP TABLE IF EXISTS adminUser;
DROP TABLE IF EXISTS repair_bus;
DROP TABLE IF EXISTS reuse_bus;
DROP TABLE IF EXISTS reuse_subcat;
DROP TABLE IF EXISTS reuse;
DROP TABLE IF EXISTS reuseSubcategory;
DROP TABLE IF EXISTS repair;
DROP TABLE IF EXISTS business;

-- adminTable
CREATE TABLE adminTable (
	adminID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	title TEXT,
	notes TEXT,
	about TEXT,
	PRIMARY KEY(adminID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- adminUser
CREATE TABLE adminUser (
	userID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	fName VARCHAR(255) DEFAULT "",
	lName VARCHAR(255) NOT NULL DEFAULT "",
	userName VARCHAR(255) NOT NULL DEFAULT "",
	password VARCHAR(255) NOT NULL DEFAULT "",
	email VARCHAR(255) NOT NULL DEFAULT "", 
	PRIMARY KEY(userID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- reuse
CREATE TABLE reuse (
    reuseID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    item VARCHAR(255) NOT NULL DEFAULT "",
    notes VARCHAR(255) DEFAULT "",
    PRIMARY KEY(reuseID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- reuseSubcategory
CREATE TABLE reuseSubcategory (
    subcatID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    itemSub VARCHAR(255) NOT NULL DEFAULT "",
    notes VARCHAR(255) DEFAULT "",
    PRIMARY KEY(subcatID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- repair
CREATE TABLE repair (
    repairID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    item VARCHAR(255) NOT NULL DEFAULT "",
    notes VARCHAR(255) DEFAULT "",
    PRIMARY KEY(repairID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- reuse_subCat
CREATE TABLE reuse_subcat (
    rid INT UNSIGNED NOT NULL,
    sid INT UNSIGNED NOT NULL,
    PRIMARY KEY(rid, sid),
    FOREIGN KEY(rid) REFERENCES reuse (reuseID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY(sid) REFERENCES reuseSubcategory (subcatID) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- business
CREATE TABLE business (
    business_id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL DEFAULT "",
    address VARCHAR(255) DEFAULT "",
    city VARCHAR (255) DEFAULT "",
    state VARCHAR (2) DEFAULT "",
    telephone VARCHAR(15) DEFAULT "",
    website VARCHAR(255) DEFAULT "",
    latitude DOUBLE,
    longitude DOUBLE,
    notes VARCHAR(255) DEFAULT "",
    PRIMARY KEY(business_id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- repair_bus
CREATE TABLE repair_bus (
    bid INT UNSIGNED NOT NULL,
    rid INT UNSIGNED NOT NULL,
    PRIMARY KEY(bid, rid),
    FOREIGN KEY(bid) REFERENCES business (business_id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY(rid) REFERENCES repair (repairID) ON DELETE CASCADE ON UPDATE CASCADE 
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- reuse_bus
CREATE TABLE reuse_bus (
    bid INT UNSIGNED NOT NULL,
    reuseID INT UNSIGNED NOT NULL,
    subcatID INT UNSIGNED NOT NULL,
    PRIMARY KEY(bid, reuseID, subcatID),
    FOREIGN KEY(bid) REFERENCES business (business_id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY(reuseID) REFERENCES reuse (reuseID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY(subcatID) REFERENCES reuseSubcategory (subcatID) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
